/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthStaffRouteImport } from './routes/auth/staff'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppAchievementsRouteImport } from './routes/_app/achievements'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppCoursesIndexRouteImport } from './routes/_app/courses/index'
import { Route as AppCommunityIndexRouteImport } from './routes/_app/community/index'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as LearnCourseSlugLessonIdRouteImport } from './routes/learn/$courseSlug.$lessonId'
import { Route as AdminCoursesIdRouteImport } from './routes/admin/courses/$id'
import { Route as AppProfileUsernameRouteImport } from './routes/_app/profile.$username'
import { Route as AppCoursesSlugRouteImport } from './routes/_app/courses/$slug'
import { Route as AppCommunityPostIdRouteImport } from './routes/_app/community/post.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthStaffRoute = AuthStaffRouteImport.update({
  id: '/auth/staff',
  path: '/auth/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityIndexRoute = AppCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRoute,
} as any)
const LearnCourseSlugLessonIdRoute = LearnCourseSlugLessonIdRouteImport.update({
  id: '/learn/$courseSlug/$lessonId',
  path: '/learn/$courseSlug/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesIdRoute = AdminCoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesSlugRoute = AppCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityPostIdRoute = AppCommunityPostIdRouteImport.update({
  id: '/community/post/$id',
  path: '/community/post/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/achievements': typeof AppAchievementsRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/staff': typeof AuthStaffRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/$slug': typeof AppCoursesSlugRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/learn/$courseSlug/$lessonId': typeof LearnCourseSlugLessonIdRoute
  '/account/': typeof AppAccountIndexRoute
  '/community/': typeof AppCommunityIndexRoute
  '/courses/': typeof AppCoursesIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/community/post/$id': typeof AppCommunityPostIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/achievements': typeof AppAchievementsRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/staff': typeof AuthStaffRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/courses/$slug': typeof AppCoursesSlugRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/learn/$courseSlug/$lessonId': typeof LearnCourseSlugLessonIdRoute
  '/account': typeof AppAccountIndexRoute
  '/community': typeof AppCommunityIndexRoute
  '/courses': typeof AppCoursesIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
  '/community/post/$id': typeof AppCommunityPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/search': typeof AppSearchRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/staff': typeof AuthStaffRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/courses/$slug': typeof AppCoursesSlugRoute
  '/_app/profile/$username': typeof AppProfileUsernameRoute
  '/admin/courses/$id': typeof AdminCoursesIdRoute
  '/learn/$courseSlug/$lessonId': typeof LearnCourseSlugLessonIdRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/community/': typeof AppCommunityIndexRoute
  '/_app/courses/': typeof AppCoursesIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
  '/_app/community/post/$id': typeof AppCommunityPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/welcome'
    | '/achievements'
    | '/leaderboard'
    | '/notifications'
    | '/search'
    | '/admin/members'
    | '/admin/submissions'
    | '/auth/reset-password'
    | '/auth/staff'
    | '/admin/'
    | '/courses/$slug'
    | '/profile/$username'
    | '/admin/courses/$id'
    | '/learn/$courseSlug/$lessonId'
    | '/account/'
    | '/community/'
    | '/courses/'
    | '/events/'
    | '/admin/courses/'
    | '/community/post/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/welcome'
    | '/achievements'
    | '/leaderboard'
    | '/notifications'
    | '/search'
    | '/admin/members'
    | '/admin/submissions'
    | '/auth/reset-password'
    | '/auth/staff'
    | '/'
    | '/admin'
    | '/courses/$slug'
    | '/profile/$username'
    | '/admin/courses/$id'
    | '/learn/$courseSlug/$lessonId'
    | '/account'
    | '/community'
    | '/courses'
    | '/events'
    | '/admin/courses'
    | '/community/post/$id'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/login'
    | '/welcome'
    | '/_app/achievements'
    | '/_app/leaderboard'
    | '/_app/notifications'
    | '/_app/search'
    | '/admin/members'
    | '/admin/submissions'
    | '/auth/reset-password'
    | '/auth/staff'
    | '/_app/'
    | '/admin/'
    | '/_app/courses/$slug'
    | '/_app/profile/$username'
    | '/admin/courses/$id'
    | '/learn/$courseSlug/$lessonId'
    | '/_app/account/'
    | '/_app/community/'
    | '/_app/courses/'
    | '/_app/events/'
    | '/admin/courses/'
    | '/_app/community/post/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthStaffRoute: typeof AuthStaffRoute
  LearnCourseSlugLessonIdRoute: typeof LearnCourseSlugLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/staff': {
      id: '/auth/staff'
      path: '/auth/staff'
      fullPath: '/auth/staff'
      preLoaderRoute: typeof AuthStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/': {
      id: '/_app/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/': {
      id: '/_app/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AppCommunityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/learn/$courseSlug/$lessonId': {
      id: '/learn/$courseSlug/$lessonId'
      path: '/learn/$courseSlug/$lessonId'
      fullPath: '/learn/$courseSlug/$lessonId'
      preLoaderRoute: typeof LearnCourseSlugLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$id': {
      id: '/admin/courses/$id'
      path: '/courses/$id'
      fullPath: '/admin/courses/$id'
      preLoaderRoute: typeof AdminCoursesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses/$slug': {
      id: '/_app/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AppCoursesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/post/$id': {
      id: '/_app/community/post/$id'
      path: '/community/post/$id'
      fullPath: '/community/post/$id'
      preLoaderRoute: typeof AppCommunityPostIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCoursesSlugRoute: typeof AppCoursesSlugRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppCommunityIndexRoute: typeof AppCommunityIndexRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppCommunityPostIdRoute: typeof AppCommunityPostIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppCoursesSlugRoute: AppCoursesSlugRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppCommunityIndexRoute: AppCommunityIndexRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppCommunityPostIdRoute: AppCommunityPostIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminMembersRoute: typeof AdminMembersRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesIdRoute: typeof AdminCoursesIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMembersRoute: AdminMembersRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesIdRoute: AdminCoursesIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthStaffRoute: AuthStaffRoute,
  LearnCourseSlugLessonIdRoute: LearnCourseSlugLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
